apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mentoring-backend.fullname" . }}
  labels:
    {{- include "mentoring-backend.labels" . | nindent 4 }}
data:
  app.conf: |
    # Application configuration
    # Add your config here
