apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mentoring-frontend.fullname" . }}
  labels:
    {{- include "mentoring-frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
    # Nginx configuration
    # Add your config here
