replicaCount: 1
image:
  tag: "dev-a6eb27c153831d4c6552dd7f32d2faece5b14705"
ingress:
  hosts:
    - host: api-dev.mentoring.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-dev-tls
      hosts:
        - api-dev.mentoring.example.com
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  - name: DATABASE_URL
    value: "postgresql://user:password@postgres-dev:5432/mentoring_dev"
  - name: REDIS_URL
    value: "redis://redis-dev:6379"
  - name: ENV
    value: "development"
