replicaCount: 1
image:
  tag: "dev-a6eb27c153831d4c6552dd7f32d2faece5b14705"
ingress:
  hosts:
    - host: dev.mentoring.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-dev-tls
      hosts:
        - dev.mentoring.example.com
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
env:
  - name: VITE_API_URL
    value: "https://api-dev.mentoring.example.com"
  - name: VITE_ENV
    value: "development"
