replicaCount: 1
image:
  tag: "dev-39201a5262037f415ca7eb07a28e7e143645984f"
ingress:
  hosts:
    - host: dev.mentoring.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-dev-tls
      hosts:
        - dev.mentoring.example.com
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
env:
  - name: VITE_API_URL
    value: "http://14.39.90.228:8083"
  - name: VITE_ENV
    value: "development"
